server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/subhradeep-rdj/microservice-config
          